name: Export Discussions

on:
  workflow_dispatch:
  #schedule:
    #- cron: '0 6 * * 1' # weekly on Monday at 6am UTC

permissions:
  contents: write

jobs:
  export:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Export discussions
        uses: ./
        with:
          token: ${{ secrets.GH_PAT }}

      - name: Commit and push
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add docs/
          git diff --cached --quiet || git commit -m "$(date +%Y-%m-%d) - Export discussions to Repo"
          git push
